//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod build_history;
pub mod eating_preferences;
pub mod ingredient;
pub mod inventory;
pub mod recipe;
pub mod recipe_ingredients_linker;
pub mod sea_orm_active_enums;
pub mod users;
