//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::build_history::Entity as BuildHistory;
pub use super::eating_preferences::Entity as EatingPreferences;
pub use super::ingredient::Entity as Ingredient;
pub use super::inventory::Entity as Inventory;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredients_linker::Entity as RecipeIngredientsLinker;
pub use super::users::Entity as Users;
