//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "eating_restrictions"
)]
pub enum EatingRestrictions {
    #[sea_orm(string_value = "Halal")]
    Halal,
    #[sea_orm(string_value = "Kosher")]
    Kosher,
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "Other")]
    Other,
    #[sea_orm(string_value = "Pescetarian")]
    Pescetarian,
    #[sea_orm(string_value = "Vegan")]
    Vegan,
    #[sea_orm(string_value = "Vegetarian")]
    Vegetarian,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "units")]
pub enum Units {
    #[sea_orm(string_value = "cup")]
    Cup,
    #[sea_orm(string_value = "g")]
    G,
    #[sea_orm(string_value = "lb")]
    Lb,
    #[sea_orm(string_value = "ml")]
    Ml,
    #[sea_orm(string_value = "oz")]
    Oz,
}
